import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { BaseService } from 'src/core/services/base.service';
import { Repository } from 'typeorm';

import { Dashboard } from '../entities/dashboard.entity';

@Injectable()
export class DashboardService extends BaseService<Dashboard> {
  constructor(
    @InjectRepository(Dashboard)
    repository: Repository<Dashboard>,
  ) {
    super(repository, Dashboard);
  }
  async findAll(): Promise<any[]> {
    return [
      {
        lastUpdated: '2019-07-26T09:59:27.089',
        href: 'https://dhis.hisptz.org/dev/api/dashboards/tFPbgxRf1bc',
        uid: 'tFPbgxRf1bc',
        created: '2016-02-01T12:56:49.152',
        name: 'Employment Status',
        displayName: 'Employment Status',
        publicAccess: '--------',
        externalAccess: false,
        itemCount: 7,
        favorite: false,
        access: {
          read: true,
          update: true,
          externalize: true,
          delete: true,
          write: true,
          manage: true,
        },
        user: { uid: 'AcSrmqQIDy0' },
        favorites: [],
        translations: [],
        userGroupAccesses: [
          {
            access: 'rw------',
            userGroupUid: 'M9CyWGINe55',
            displayName: 'HISPTZ Staffs',
            uid: 'M9CyWGINe55',
          },
        ],
        attributeValues: [],
        dashboardItems: [
          {
            lastUpdated: '2018-08-03T14:25:37.031',
            uid: 'zFnZNKX7cLJ',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/zFnZNKX7cLJ',
            created: '2016-02-03T02:59:19.485',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            lastUpdatedBy: { uid: 'DkR8reoFU9i' },
            chart: { uid: 'MTWXrZKjPRa' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
          {
            lastUpdated: '2018-03-05T16:16:01.753',
            uid: 'otxQlKW9WI1',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/otxQlKW9WI1',
            created: '2016-02-03T02:53:42.874',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'cbnWOXfp9vW' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
          {
            lastUpdated: '2016-11-08T12:38:42.990',
            uid: 'wZK5CdXVJKt',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/wZK5CdXVJKt',
            created: '2016-02-03T02:53:19.584',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'x1cWTFjrxVd' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
          {
            lastUpdated: '2017-03-29T08:50:35.044',
            uid: 'bBitVEBVOu2',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/bBitVEBVOu2',
            created: '2016-02-03T02:54:04.799',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'CCIJuYfJqAG' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
        ],
        userAccesses: [],
      },
      {
        lastUpdated: '2019-07-26T09:59:27.089',
        href: 'https://dhis.hisptz.org/dev/api/dashboards/tFPbgxRf1bc',
        uid: 'tFPbgxRf1b1',
        created: '2016-02-01T12:56:49.152',
        name: 'History',
        displayName: 'History',
        publicAccess: '--------',
        externalAccess: false,
        itemCount: 7,
        favorite: false,
        access: {
          read: true,
          update: true,
          externalize: true,
          delete: true,
          write: true,
          manage: true,
        },
        user: { uid: 'AcSrmqQIDy0' },
        favorites: [],
        translations: [],
        userGroupAccesses: [
          {
            access: 'rw------',
            userGroupUid: 'M9CyWGINe55',
            displayName: 'HISPTZ Staffs',
            uid: 'M9CyWGINe55',
          },
        ],
        attributeValues: [],
        dashboardItems: [
          {
            lastUpdated: '2018-03-05T16:16:01.753',
            uid: 'otxQlKW9WI1',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/otxQlKW9WI1',
            created: '2016-02-03T02:53:42.874',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'cbnWOXfp9vW' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
          {
            lastUpdated: '2016-11-08T12:38:42.990',
            uid: 'wZK5CdXVJKt',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/wZK5CdXVJKt',
            created: '2016-02-03T02:53:19.584',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'x1cWTFjrxVd' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
          {
            lastUpdated: '2017-03-29T08:50:35.044',
            uid: 'bBitVEBVOu2',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/bBitVEBVOu2',
            created: '2016-02-03T02:54:04.799',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'CCIJuYfJqAG' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          }
        ],
        userAccesses: [],
      },
      /*{
        lastUpdated: '2019-07-26T09:59:27.089',
        href: 'https://dhis.hisptz.org/dev/api/dashboards/tFPbgxRf1dc',
        uid: 'tFPbgxRf1dc',
        created: '2016-02-01T12:56:49.152',
        name: 'Training',
        displayName: 'Training',
        publicAccess: '--------',
        externalAccess: false,
        itemCount: 7,
        favorite: false,
        access: {
          read: true,
          update: true,
          externalize: true,
          delete: true,
          write: true,
          manage: true,
        },
        user: { uid: 'AcSrmqQIDy0' },
        favorites: [],
        translations: [],
        userGroupAccesses: [
          {
            access: 'rw------',
            userGroupUid: 'M9CyWGINe55',
            displayName: 'HISPTZ Staffs',
            uid: 'M9CyWGINe55',
          },
        ],
        attributeValues: [],
        dashboardItems: [
          {
            lastUpdated: '2018-03-05T16:16:01.753',
            uid: 'otxQlKW9WI1',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/otxQlKW9WI1',
            created: '2016-02-03T02:53:42.874',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'cbnWOXfp9vW' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
          {
            lastUpdated: '2016-11-08T12:38:42.990',
            uid: 'wZK5CdXVJKt',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/wZK5CdXVJKt',
            created: '2016-02-03T02:53:19.584',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'x1cWTFjrxVd' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          },
          {
            lastUpdated: '2017-03-29T08:50:35.044',
            uid: 'bBitVEBVOu2',
            href: 'https://dhis.hisptz.org/dev/api/dashboardItems/bBitVEBVOu2',
            created: '2016-02-03T02:54:04.799',
            type: 'CHART',
            externalAccess: false,
            contentCount: 1,
            shape: 'FULL_WIDTH',
            interpretationCount: 0,
            interpretationLikeCount: 0,
            favorite: false,
            access: {
              read: true,
              update: true,
              externalize: true,
              delete: true,
              write: true,
              manage: true,
            },
            chart: { uid: 'CCIJuYfJqAG' },
            favorites: [],
            reports: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            resources: [],
            users: [],
            userAccesses: [],
          }
        ],
        userAccesses: [],
      },*/
    ];
  }
}
